apiVersion: dipterv.my.domain/v1beta1
kind: Servicegraph
metadata:
  name: servicegraph-easyfe-heavybe
  namespace: default
spec:
  nodes:
    - name: front-end
      replicas: 2
      port: 80
      nodePort: 30000
      resources:
        memory: 1000
        cpu: 2000
      endpoints:
        - path: /only-frontend
          cpuLoad: 10
          delay: 0
        - path: /to-backend
          cpuLoad: 50
          delay: 0
          callouts:
            - url: back-end:80/heavy

    - name: back-end
      replicas: 1
      port: 80
      resources:
        memory: 1000
        cpu: 500
      endpoints:
        - path: /heavy
          cpuLoad: 150
          delay: 0