apiVersion: dipterv.my.domain/v1beta1
kind: Servicegraph
metadata:
  name: servicegraph-easyfe-heavybe
  namespace: default
spec:
  nodes:
    - name: front-end
      replicas: 2
      port: 80
      nodePort: 30000
      resources:
        memory: 200
        cpu: 200
      endpoints:
        - path: /only-frontend
          cpuLoad: 1
          delay: 0
        - path: /to-backend
          cpuLoad: 1
          delay: 0
          callouts:
            - url: back-end:80/heavy

    - name: back-end
      replicas: 3
      port: 80
      resources:
        memory: 400
        cpu: 600
      endpoints:
        - path: /heavy
          cpuLoad: 40
          delay: 2000
